classes {
    goal {
        style: {
            double-border: true
            stroke: "#f4a261"
        }
    }
}

dotnet: Dotnet
dotnet.fp: Functional Programming


back: Backend
back.aspnet: ASP.NET Core
back.orm: ORM

dotnet.s21-1: Computer Internals {
    link: google.com
}

dotnet.s21-2: .NET Internals & Versions 

dotnet.s21-mm: .NET	Memory model
dotnet.s21-1 -> dotnet.s21-mm
dotnet.s21-2 -> dotnet.s21-mm

dotnet.fp.s21-4: Functional Programming in F\#
dotnet.s21-2 -> dotnet.fp.s21-4

dotnet.fp.s21-monads: Monads
dotnet.fp.s21-4 -> dotnet.fp.s21-monads

dotnet.s21-async: async/await
dotnet.s21-mm -> dotnet.s21-async
dotnet.fp.s21-monads -> dotnet.s21-async

dotnet.s21-reflection: Reflection + Serialization/Deserialization
dotnet.s21-2 -> dotnet.s21-reflection

back.aspnet.s21-w: ASP.NET Core Basics
back.aspnet.s21-w.class: goal
dotnet.s21-async -> back.aspnet.s21-w

back.aspnet.s21-di: Dependency Injection

back.orm.s21-et: Expression Trees
dotnet.s21-2 -> back.orm.s21-et
dotnet.s21-reflection -> back.orm.s21-et

back.orm.s21-q: IQueryable, IQueryProvider
back.orm.s21-et -> back.orm.s21-q

back.orm.s21-ef: Entity Framework
back.aspnet.s21-di -> back.orm.s21-ef
back.orm.s21-q -> back.orm.s21-ef

back.aspnet.s21-g: ASP.NET Core MVC & WebAPI
back.aspnet.s21-g.class: goal

dotnet.s21-exception -> back.aspnet.s21-g
back.aspnet.s21-w -> back.aspnet.s21-g
back.aspnet.s21-di -> back.aspnet.s21-g
back.orm.s21-ef -> back.aspnet.s21-g

#dotnet.s21-14: Dynamic 
#dotnet.s21-2 -> dotnet.s21-14

#dotnet.s21-15: Бенчмарки	

dotnet.s21-memory: Memory
dotnet.s21-1 -> dotnet.s21-memory

dotnet.s21-exception: Exceptional Exceptions
back.orm.s21-ef -> dotnet.s21-exception
dotnet.s21-memory -> dotnet.s21-exception