name: .NET

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        working-directory: ./hands-on/2/1
        run: dotnet restore
      - name: Build
        working-directory: ./hands-on/2/1
        run: dotnet build --configuration Release --no-restore
      - name: Test CSharp
        working-directory: ./hands-on/2/1/Tests.CSharp
        run: dotnet test --no-restore
      - name: Test FSharp
        working-directory: ./hands-on/2/1/Tests.FSharp
        run: dotnet test --no-restore        